extends:
  - airbnb-base
  - airbnb-typescript/base
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  project: ./tsconfig.eslint.json
  extraFileExtensions:
    - .json
rules:
  import/prefer-default-export: 0
  class-methods-use-this: 0
  max-classes-per-file: 0
  no-console: 'off'
  '@typescript-eslint/dot-notation': 'off'
  'import/no-extraneous-dependencies': 'off'
  '@typescript-eslint/no-unused-vars': 'off'
  'tprefer-destructuring': 'off'
  'no-else-return': 'off'
  'no-plusplus': 'off'
  'no-await-in-loop': 'off'
  'import/no-import-module-exports': 'off'
  'no-case-declarations': 'off'
  'consistent-return': 'off'
  'import/extensions': 'off'
  'prefer-destructuring': 'off'
  'new-cap': 'off'
  'no-async-promise-executor': 'off'
  'no-promise-executor-return': 'off'
  'no-underscore-dangle': 'off'
  'prefer-promise-reject-errors': 'off'
  'eqeqeq': 'off'
  'arrow-body-style': 'off'
  'import/no-cycle': 'off'
  '@typescript-eslint/return-await': 'off'
  'import/no-relative-packages': 'off'
  'no-throw-literal': 'off'
  'react-native/no-inline-styles': 'off' # Desativa a verificação de estilos inline (opcional)
  'react-native/split-platform-components': 'off' # Desativa verificações específicas do React Native (opcional)
  'react-native/no-color-literals': 'off' # Desativa verificações de literais de cor (opcional)
  'react-native/no-raw-text': 'off' # Desativa verificações de texto bruto (opcional)
  'react-native/no-raw-colors': 'off'

custom:
  react-native-shadow-color:
    - properties:
        - 'shadowColor'

plugins:
  - prettier
ignorePatterns:
  - '**/*.json'
  - 'src/package.json'
